### ISSUE TITLE
Enabling/Disabling SSL in plugin does not work

### ISSUE THREAD

**Issue by alanking** [irods/irods_auth_plugin_pam_interactive#16]
Whenever I try to use the plugin with SSL disabled (but the client and server are configured so that it *can* be used), the plugin attempts to enable/disable SSL when sending data to the server just like the pam_password plugin. However, this doesn't seem to be working because I get an "SSL shutdown" error every time the client disconnects.

If I remove the logic for enabling/disabling SSL, everything works fine. However, we need to require SSL for this plugin as sensitive information is being sent from the client to the server and so must be encrypted.

This is a blocker for release.

**Comment by alanking** [comment]
After discussion at the March 2024 Authentication Working Group, we have decided that the plugin should allow usage without SSL, but log annoying messages for the administrator and possibly even require a configuration which explicitly allows for "insecure" authentications.

**Comment by alanking** [comment]
Changes in #36 fixes the bug part of this, but the previous comment suggests we want to allow using the plugin without SSL. Leaving this open until we decide what we want to do with that.

**Comment by trel** [comment]
from the minutes...
https://github.com/irods-contrib/irods_working_group_authentication/blob/main/20240326-minutes.md

> "Default is SSL - active option to disable SSL"

So... agreed for now - leaving open makes sense.

**Comment by alanking** [comment]
Okay. Given that this issue is labeled as a bug, I think it would be a cleaner separation to close this one and open a new issue as an enhancement to allow not using SSL (or, as the minutes suggest, a configuration). Thoughts?

**Comment by trel** [comment]
I think that makes sense.

**Comment by alanking** [comment]
Great. Created https://github.com/irods/irods_auth_plugin_pam_interactive/issues/40 for the enhancement. Closing this one.
