### ISSUE TITLE
Packaging is wrong in several ways

### ISSUE THREAD

**Issue by alanking** [irods/irods_auth_plugin_pam_interactive#17]
I goofed up the packaging in https://github.com/irods/irods_auth_plugin_pam_interactive/commit/8bfa0f6be084be39cf7f0f849f2e6f897913f5f4 :(

Only 1 package is produced and we need to be producing 2 packages: one for the client (just the client-side plugin) and one for the server (which includes both the client and server plugins, as well as any tests which will come in the future).

Also, there may be an issue with upgrading/replacing installed files which already exist. May or may not be related.

This is a blocker for release.

**Comment by SwooshyCueb** [comment]
Should be fixed with #21. If further changes are needed, please open a new issue.
