### ISSUE TITLE
`auth_check_wrapper.cpp`: `strlen` usage is a bit wonky

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_auth_plugin_pam_interactive#24]
This line in `auth_check_wrapper.cpp` is of some concern:
https://github.com/irods/irods_auth_plugin_pam_interactive/blob/f07902328fc4b686b2f79da152c8fb89f579696c/src/auth_check_wrapper.cpp#L16

- `strlen` is in the `std::` namespace, so should be referred to as `std::strlen`.
- `std::strlen` comes from `<cstring>`, but `<cstring>` is never `#include`d.
- `std::strlen` returns `std::size_t`, not `uint32_t`. It appears intentional that `n` is a `uint32_t`, so `static_cast` should be used.
- `uint32_t` is in the `std::` namespace, so should be referred to as `std::uint32_t`.
- `std::uint32_t` comes from `<cstdint>`, but `<cstdint>` is never `#include`d.

**Comment by korydraughn** [comment]
@SwooshyCueb Please close if completed.
