### ISSUE TITLE
Make PAM stack configurable

### ISSUE THREAD

**Issue by alanking** [irods/irods_auth_plugin_pam_interactive#37]
Currently, the PAM stack used by the plugin is hard-coded to "irods" (which should be found in `/etc/pam.d/irods`). It might be a good idea to allow pointing at a different PAM stack file via a configuration. This would be especially useful for testing, but might have some use in real deployments.

**Comment by alanking** [comment]
When the "irods" PAM stack does not exist (or, as I discovered while working on this, whatever PAM stack is fed to the PAM session), it seems that the flow defaults to using the **pam_unix** module. We should consider giving an error back whenever PAM is not configured in the manner expected by the plugin.

**Comment by trel** [comment]
Can the plugin know about such things?

**Comment by alanking** [comment]
Well, what it boils down to is a call to `pam_start` where the `pam_stack_name` will become the `service_name` argument: https://linux.die.net/man/3/pam_start

Here's what the manual says:
> The service_name argument specifies the name of the service to apply and will be stored as PAM_SERVICE item in the new context. The policy for the service will be read from the file /etc/pam.d/service_name or, if that file does not exist, from /etc/pam.conf. 

Here's the `/etc/pam.conf` file in my more-or-less-vanilla setup (it's empty except for comments):
```
$ cat /etc/pam.conf 
# ---------------------------------------------------------------------------#
# /etc/pam.conf                                                              #
# ---------------------------------------------------------------------------#
#
# NOTE
# ----
#
# NOTE: Most program use a file under the /etc/pam.d/ directory to setup their
# PAM service modules. This file is used only if that directory does not exist.
# ---------------------------------------------------------------------------#

# Format:
# serv. module     ctrl       module [path]     ...[args..]                  #
# name  type       flag                                                      #
```

So, I guess if the service is not defined in `/etc/pam.d` or `/etc/pam.conf`, PAM just does whatever it wants. I haven't gotten to the bottom of that yet. In any case, it's far past the point of control for our plugin. So I guess we cannot return an error in that case.

So that raises the question... *should* the plugin allow for switching the PAM stack name that we use? If, for instance, an administrator configures a `pam_stack_name` which does not exist and `iinit` now allows for password authentication (I have demonstrated this in my setup), is that okay? I suppose it's no different from installing the plugin and then not creating/configuring an "irods" stack...

**Comment by trel** [comment]
> If, for instance, an administrator configures a `pam_stack_name` which does not exist and `iinit` now allows for password authentication (I have demonstrated this in my setup), is that okay? I suppose it's no different from installing the plugin and then not creating/configuring an "irods" stack...

Agreed, those sound the same and the plugin can't know or be held responsible...?

**Comment by korydraughn** [comment]
So if the service name isn't found, PAM falls back to password authentication?

**Comment by alanking** [comment]
I don't know whether this differs between platforms or versions, but this is how it behaves on our supported platforms, yes.

**Comment by korydraughn** [comment]
At the very least, the user can't bypass authentication. The behavior probably varies across platforms.

I think the current behavior is fine.

**Comment by alanking** [comment]
Seems I spoke too soon. I tried this out on Rocky Linux 9 and found that an error is returned on that platform. I was testing on Ubuntu before. So, it does vary from platform to platform. 

Anyway, even if this exhibited undesirable behavior, again, there's not really much we can do because this is a PAM issue, not a plugin issue.

**Comment by korydraughn** [comment]
I agree. Making sure the deployment is in a good state is the job of the admin.
