### ISSUE TITLE
Demonstrate / Document Kerberos flow

### ISSUE THREAD

**Issue by alanking** [irods/irods_auth_plugin_pam_interactive#41]
If we can demonstrate a Kerberos authentication flow that is similar if not identical to the one used in the Kerberos auth plugin (https://github.com/irods/irods_auth_plugin_kerberos), we can archive that repository and point people to using this plugin.

The Kerberos PAM module most places use is called `pam_krb5`. Check out these resources:

- https://www.oreilly.com/library/view/linux-security-cookbook/0596003919/ch04s17.html
- https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/4/html/reference_guide/s1-kerberos-pam#s1-kerberos-pam
- https://docs.oracle.com/cd/E53394_01/html/E54787/pam-32.html
- https://linux.die.net/man/8/pam_krb5

If the auth flow can be successfully demonstrated, we need to document the process so that it can be reproduced by others, and add tests (perhaps just copy the tests from the Kerberos auth plugin repository?).

**Comment by alanking** [comment]
I found this tutorial: http://techpubs.spinlocksolutions.com/dklar/kerberos.html#intro

It was referenced in the "Additional references" of the official Kerberos documentation: http://web.mit.edu/kerberos/krb5-current/doc/admin/install.html

I was able to authenticate via `iinit` with `pam_interactive` and a PAM stack using `pam_krb5`. The short version is...

1. Set up Kerberos server and realm just like the tutorial says. I guess we don't need to worry about this part for documentation, but we will want to understand this for testing purposes. I think that the test hook for Kerberos plugin was based off this tutorial because the steps are uncanny...  https://github.com/irods/irods_auth_plugin_kerberos/blob/main/irods_consortium_continuous_integration_test_hook.py
2. Create an "unprivileged principal" for your user:
```bash
addprinc -policy user alan # This is going to prompt you for a password, this is the password you will use
```
3. Create a Linux user and lock the user account 
```bash
useradd -s /bin/bash -m alan
# Give a different Linux password than the Kerberos password so you can be sure you're authenticating with Kerberos, not Linux
usermod -p apass alan
```
4. Modify the `irods` PAM stack to look like this:
```bash
# I took this from the tutorial's /etc/pam.d/common-auth example
auth    [success=2 default=ignore]      pam_krb5.so minimum_uid=1000
auth    [success=1 default=ignore]      pam_unix.so nullok_secure try_first_pass
auth    requisite                       pam_deny.so
auth    required                        pam_permit.so
```
5. Run `iinit` as the Linux user with `pam_interactive` as your auth scheme:
```
$ iinit # enter your Kerberos password
Password:
```
Try entering the Linux password instead of the Kerberos password and watch it fail.

**Comment by korydraughn** [comment]
Yep. I recognize those web pages. Good stuff.

So now that you've demonstrated success. What are we missing? Documentation? Tests? Or maybe that's unnecessary / out-of-scope because it's PAM?

**Comment by alanking** [comment]
Right, I think we should at least put the steps in the README like we did for the `pam_password` example. I *think* this demonstration is enough for this plugin to act as a drop-in replacement for the Kerberos plugin which was not released for 4.3.

It may behoove us to actually put these PAM stack files in the repository in addition to the documentation under an examples directory or something, but I'm not sure how helpful that would be.

As for testing, I was originally thinking of putting a suite of tests for Kerberos in this repo, but I think I agree that it may be unnecessary / out-of-scope. Maybe we just resolve this issue by documenting the steps and we can do more later if there is community demand. Thoughts?

**Comment by korydraughn** [comment]
After some discussion, we decided that documentation is good enough.

Please open an issue for **considering** the addition of kerberos tests.

**Comment by alanking** [comment]
I created #46 for consideration of adding Kerberos testing.
