### ISSUE TITLE
Hard-coded path to `/var/lib/irods` in test hook

### ISSUE THREAD

**Issue by alanking** [irods/irods_auth_plugin_pam_interactive#48]
https://github.com/irods/irods_auth_plugin_pam_interactive/blob/b05360545d6dbb16e0eadf2745e39d3d0b5438d8/irods_consortium_continuous_integration_test_hook.py#L40-L41

Let's see if there's a better way to get at that path.

**Comment by alanking** [comment]
I think this issue goes beyond the scope of this plugin. I created this issue for discussion about how we should address this across all of our plugins: https://github.com/irods/irods_testing_environment/issues/229

For this issue, let's just make some local functions to abstract this and we can solve the larger problem for all the plugins in the other issue.

**Comment by korydraughn** [comment]
Agreed.
